baseURL = ""
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "5"
theme = ""
title = "DJ Request Live!"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = ""
name = "Request It!"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = ""
description = "This is meta description"
logo = ""
search = false
social = []
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = false
preloader = ""
